### ISSUE TITLE
" 'JNWScrollView.h' file not found" after Cocoapod install

### ISSUE THREAD

**Issue by tsfischer** [jwilling/JNWCollectionView#159] opened 2016-02-10 17:18 UTC
Is there any trick to using this with Cocoapods in a Swift project? Upon building I'm getting the error mentioned in the issue title.

Since this is a swift project with swift pods I have 'use_frameworks!' set in the podfile which may or may not be relevant here.

Thanks!

**Comment by jwilling** [comment] 2016-02-13 09:01
Unfortunately I don't have much experience with Swift & CocoaPods. The podspec lists `JNWScrollView` as a dependency. With that frameworks flag enabled does it attempt to turn `JNWScrollView` into a framework as well?

**Comment by bmichotte** [comment] 2016-02-29 15:00
I get it to work by changing `#import "JNWScrollView.h"` by `#import <JNWScrollView/JNWScrollView.h>` in JNWCollectionViewFramework.h

Could you modify it @jwilling ?

**Comment by jwilling** [comment] 2016-03-06 10:00
@bmichotte The problem is that I can't change it to a framework import since it technically isn't a framework. It would work for the CocoaPods build but would break the framework build. I'll try to come up with a fix if I can find the time.

**Comment by bmichotte** [comment] 2016-03-06 10:15
@jwilling  The following works
```objc
#if defined(COCOAPODS)
#import <JNWScrollView/JNWScrollView.h>
#else
#import JNWScrollView.h
#endif
```

**Comment by jwilling** [comment] 2016-03-07 13:36
Should be fixed thanks to @bmichotte.

**Closed by jwilling** 2016-03-07 13:36 UTC
